### PR TITLE
Use libunicorn.so.2 as fallback path

### PR DESCRIPTION
**Pull request by rhelmot**
This adds support for FreeBSD.

### CODE REVIEW

**Comment by wtdcode** [comment]
Why not add a new key in `_lib`?

Ref: https://stackoverflow.com/questions/446209/possible-values-from-sys-platform

**Comment by rhelmot** [comment]
That would work, but it remains that "libunicorn.so" is just straight up never correct in any situation, right?

**Comment by wtdcode** [comment]
> That would work, but it remains that "libunicorn.so" is just straight up never correct in any situation, right?

Okay, make sense.

**Comment by wtdcode** [comment]
But you should target dev branch ;)

**Pull request closed without merging**
