### PR TITLE
add ifdef for compiling with mingw

### PR DESCRIPTION
**Pull request by cseagle**

### CODE REVIEW

**Comment by danghvu** [comment]
Do you know if this flag works for all window version ?

**Comment by cseagle** [comment]
I have no way to test across all Windows versions, but it fixes both the 32 and 64 bit builds on Windows 7.

**Comment by danghvu** [comment]
I suppose removing the inclusion will work for you too?

**Comment by cseagle** [comment]
That's fine as long as it doesn't break other things. You call munmap later in that file if I recall correctly.

**Comment by danghvu** [comment]
Not anymore, see latest commit. Thanks!

**Pull request closed without merging**
