### PR TITLE
fix msys2 and travis builds

### PR DESCRIPTION
**Pull request by stephengroat**
@aquynh this should fix msys2 and travis builds

travis has moved to `xenial` by default (now that `trusty` is EOL)

### CODE REVIEW

**Comment by aquynh** [comment]
is this ready to get merged yet?

**Comment by stephengroat** [comment]
Ready to go

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
can we have the Appveyor artifacts now?

**Pull request merged**
