### PR TITLE
Unicord fails to emulate VMOV on ARM (actually Thumb)

### PR DESCRIPTION
**Pull request by mkravchik**

### CODE REVIEW

**Comment by aquynh** [comment]
great, but there are still some issues:

- do "chmod +x vmov.py" to make your script executable.

- this still needs assert to verify the correctness of this instruction. you may want to check for the new values of related registers. see other Python testcases under `tests/regress` for reference.

please fix these issues so i can merge it, thanks.

**Comment by petevine** [comment]
Thanks @mkravchik, I'm going to use that name for my next project ;)

**Comment by mkravchik** [comment]
What exactly you are going to use and for what project?

**Comment by petevine** [comment]
Not sure yet, probably something about heart surgery or maybe musical instruments... Does that strike a cord? :)

**Pull request closed without merging**
