### PR TITLE
build: Fixes for Haiku

### PR DESCRIPTION
**Pull request by kallisti5**
* Haiku is fully posix, so can be lumped together with most unix cases

### CODE REVIEW

**Comment by aquynh** [comment]
Cool, does this make Unicorn fully work on Haiku now?

**Comment by wtdcode** [comment]
Cool, could you target dev branch?

**Comment by kallisti5** [comment]
>  Cool, does this make Unicorn fully work on Haiku now?

1.0.2 worked under Haiku, these are mostly some minor build regressions in 2.0.2.

> Cool, could you target dev branch?

Ok.   A bit reverse the normal "dev in master/main and stable in branches"

**Comment by wtdcode** [comment]
@OscarL 

This has been fixed here: https://github.com/unicorn-engine/unicorn/commit/cef7d7d0fbefb0c6e1da7eaf782bef36cf8ad64c

**Comment by wtdcode** [comment]
The small divergence between master and dev leads to some bad history for this PR so I cherry picked your commit here: 661b2b6e3d1c1b62eef1373ee8b53e6fcc16bc7a

**Comment by wtdcode** [comment]
Undo cherry-pick and merged, thanks!

**Pull request merged**
