### PR TITLE
Revert "Changed constatns in ruby gdt example"

### PR DESCRIPTION
**Pull request by felberj**
Reverts unicorn-engine/unicorn#876

Experimenting with the value seemed like that it is not correct. It might be that the documentation on osdev is wrong or the emulator implementation is different.

@sashs

### CODE REVIEW

**Comment by aquynh** [comment]
@sashs, so what is a good fix for this?

**Comment by sashs** [comment]
Hey,
apologize the delay. I will try to check that by next weekend.

**Comment by lunixbochs** [comment]
Usercorn's GDT code is fully working now if you need another reference:

https://github.com/lunixbochs/usercorn/blob/master/go/arch/x86/linux.go#L127-L134
https://github.com/lunixbochs/usercorn/blob/master/go/arch/x86/linux.go#L56

**Comment by wtdcode** [comment]
Closed due to uc2 beta release.

**Pull request closed without merging**
