### PR TITLE
fix Cross-compile for Android

### PR DESCRIPTION
**Pull request by Jaysonicc**

### CODE REVIEW

**Comment by zengming00** [comment]
Hello, I am using this version of ndk
```
wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
```
I follow the tutorial and prompt me when I start compiling
```
14 is less than minimum platform for arm (16)
```
So I additionally specified APILEVEL to work properly
```
NDK=~/android-ndk-r20 APILEVEL=android-16 ./make.sh cross-android arm
```
However, an error still occurred when the compilation progressed to the compile sample stage.
Can you tell me what version of ndk you are using?

**Comment by Jaysonicc** [comment]
The ndk version I use is 17.2.4988734

**Comment by Jaysonicc** [comment]
I tested that ndk21 can also be built

**Comment by wtdcode** [comment]
Link to #1217 for android build.

**Comment by wtdcode** [comment]
Fixed in ae1b6ad89be5546d0062115efb6eebd6a74cffde and check [wiki](https://github.com/unicorn-engine/unicorn/wiki/Compile#cross-build-with-ndk) for details.

**Pull request closed without merging**
