### PR TITLE
python: Fix exception in finalizer at exit

### PR DESCRIPTION
**Pull request by bennofs**
Sometimes, the finalizer for an `UcRef` runs so late that the members of the
module have already been set to `None`. We need to make sure that we don't
depend on anything in the module, or we risk getting a Exception when we try
to access the `release_handle` method of `None` (`Uc`).

### CODE REVIEW

**Comment by aquynh** [comment]
this is interesting, but how can we reproduce this issue?

**Comment by bennofs** [comment]
@aquynh I added a script (with docker, in case that this is python-version specific but you can also try to run it without the script) + source code at https://github.com/bennofs/repros/tree/master/unicorn/%23873

Note that reproducing this is quite fragile. For example, just changing the name of the `angr.state_plugins.unicorn_engine`  module to `angr2.state_plugins.unicorn_engine` or `angr.s.unicorn_engine` makes the error disappear. I suspect that there is some internal hash table and thus the order in which modules are dropped is depending on a hash value.

**Comment by bennofs** [comment]
Sample run:

```
d-cube:/c/r/u/#873 (master=) python2 none-type-error.py 
Exception AttributeError: "'NoneType' object has no attribute 'release_handle'" in <bound method UcCleanupManager._finalizer of <unicorn.unicorn.UcCleanupManager object at 0x7fdc62355d90>> ignored
```

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
