### PR TITLE
Fuzz

### PR DESCRIPTION
**Pull request by catenacyber**
Integration with oss-fuzz

- One fuzz target per architecture (buffer is pure x86 or ARM, not with options as done in capstone)
- Only fuzzes `uc_emu_start` (seemed relevant)
- Some minor modification to samples/Makefile to make it work

### CODE REVIEW

**Comment by catenacyber** [comment]
Looks ok now.
There is a lot of undefined behaviors...
Any idea on how to generate a corpus ?

**Comment by aquynh** [comment]
great, thanks for doing this again!

any change on this, compared with the pull req to OSSFuzz?

**Comment by aquynh** [comment]
what do you think about moving fuzz/ into tests/?

**Comment by catenacyber** [comment]
Good idea :-)

**Comment by aquynh** [comment]
merged, thanks!

please add your name to https://github.com/unicorn-engine/unicorn/blob/master/CREDITS.TXT, too.

**Pull request merged**
