### PR TITLE
CI Cleanup

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by aquynh** [comment]
why do we have cmocka issue with Appveyor?

**Comment by stephengroat** [comment]
there seems to be an issue with compile https://ci.appveyor.com/project/aquynh/unicorn/builds/20214635/job/3fsovncoxgf52m06#L526

i'll look into it on this pr

**Comment by stephengroat** [comment]
determined the issue.

the dll used to be named `cmocka.dll`. now it's named `libcmocka.dll` and can't be found at runtime. trying to determine if this is a msys2 wide change, i'm not sure

**Comment by stephengroat** [comment]
@aquynh should be good to go now, upstream issue fixed

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
