### PR TITLE
Fixes to make python distribution for windows work

### PR DESCRIPTION
**Pull request by rhelmot**
I was successfully able to build and install working wheels for both mingw64 and mingw32.

Note that there's actually a bug in the msys distribution of python preventing bdist_wheel from working correctly. I submitted a patch to address this. https://github.com/Alexpux/MINGW-packages/pull/1899

Should address #671

### CODE REVIEW

**Comment by aquynh** [comment]
some concerns about this approach:

- it seems users are forced to use Msys environment to install, and from my experience Msys & its Python is very slow, and buggy
- this always recompiles unicorn.dll

i still think that it is simpler if we ask users to explicitly copy all the required DLLs (including dependencies & `unicorn.dll`) into `prebuilt/` directory (which will be picked up to put into the same final directory with `unicorn.py`), then run `python setup.py install` from whatever they want.

thoughts?

**Comment by rhelmot** [comment]
That's the thing, it packages the full set of dependencies! You can run a
binary distribution of this package on pure windows Python; I tested this.

I'm seeing the incremental builds work correctly...

**Comment by aquynh** [comment]
to run this on native Windows Python, you have to copy dependencies to `c:\python35\bin`, which is not a nice approach. it is easier if we just put all the DLLS into `prebuilt/`, and get setup.py pick them up from there.

**Comment by aquynh** [comment]
Or we can keep what this PR is doing, but add prebuilt/ support. So users can either run this in Msys (uses Msys DLLs) or from native Python (uses prebuilt DLLs).

But lets make the core compilation non-default, so users without Msys can still run it

**Comment by rhelmot** [comment]
FYI: I have not forgotten this, but I'm currently overloaded with work and will be busy an traveling for the next week.

**Comment by stephengroat** [comment]
after working a lot with the build system, i'm not sure this is the best idea.

python is a consumer of the C library, it seems a little bit backwards to have python create a dll. also, if a windows solution is put into place, a *nix and darwin solution should also probably be added

**Comment by rhelmot** [comment]
Two responses:

- unfortunately, this library has to be responsible for its own C library, since without it it just doesn't work. Capstone, for example, used to be distributed without its C library, and every other issue I got on a tool that depended on capstone was "it doesn't work" which was because capstone refused to import because it got installed without its c library. 

- we already do support doing this for win32 and Darwin! This patch is an update to an existing system I designed to do this exactly.

**Comment by rhelmot** [comment]
I pushed a thing so that people can copy the windows support DLLs into bindings/python/prebuilt and they'll be packaged up with the install.

**Comment by aquynh** [comment]
great, but i still see the call to `subprocess.call(cmd, env=new_env)`, so the core is always compiled in any cases?

**Comment by rhelmot** [comment]
If you don't want to compile the core, you shouldn't be using a source distribution - I specifically set up everything so binary distributions (`python setup.py bdist_wheel register upload` on the developer end, `pip install unicorn` on the user end) work correctly.

**Comment by aquynh** [comment]
how about this scenario: Windows users copy the dependency libraries to prebuilt/, then run "python setup.py install". this would fail, because of this compilation requires Msys, which most users do not have on their machines.

**Comment by rhelmot** [comment]
I'm not sure why you're insistent on supporting the scenario where a user who does not have a build environment set up uses anything other than a packaged binary distribution, but alright. This should support that.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
