### PR TITLE
Use base instead of selector for 32/64 segment regs - we might consid…

### PR DESCRIPTION
**Pull request by ohjeongwook**
…er making separate UC_X86_REG_*S_SELECTOR code for selector manipulation

### CODE REVIEW

**Comment by JonathonReinhart** [comment]
Sorry, but this is wrong. This has been proposed several times before (#454). See #422 for an explanation.

@aquynh This needs to be put in a FAQ or something.

**Comment by aquynh** [comment]
i am working on this. the target is solve this issue so that a FAQ is not needed anymore.

**Comment by cseagle** [comment]
#478 may address some of this

**Comment by aquynh** [comment]
this is addressed now, thanks!

**Pull request closed without merging**
