### PR TITLE
Added MIPS support and added projects for all samples.

### PR DESCRIPTION
**Pull request by xorstream**
Added MIPS support and added projects for all samples.

Everything builds with 0 warnings and errors for me in VS2012, but the mips sample fails.
This, of course, this needs looking into but will have to wait till tomorrow.

### CODE REVIEW

**Comment by aquynh** [comment]
you are 1 commit behind when you pushed to your Github fork, thus the conflict. can you pull the latest code, and try again?

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
now this breaks some original tests on Linux: https://travis-ci.org/unicorn-engine/unicorn/builds/194338417

**Comment by xorstream** [comment]
that link gives me "The repository at unicorn-engine/unicorn was not found."

**Comment by aquynh** [comment]
you can try again with https://travis-ci.org/unicorn-engine/unicorn/

**Pull request merged**
