### PR TITLE
remove call to restore_eflags (#496)

### PR DESCRIPTION
**Pull request by lunixbochs**
this outright breaks conditionals and needs to be done in a different way

### CODE REVIEW

**Comment by aquynh** [comment]
does this fix the issues of https://gist.github.com/jbremer/6c0aa8253304f7f5b385 ? (reported in #496 by @jbremer)

**Comment by lunixbochs** [comment]
yep, the 0xc7 case behaves correctly under this patch as described in the original issue

**Comment by aquynh** [comment]
@zaddach, do you have any comments?

**Comment by zachriggle** [comment]
This also fixes the issues I'm seeing in the emulator when single-stepping through conditionals #499, which is tested by #501 and #511.

The test in #501 passes after this change.

The test in #511 passes after this change.

**Comment by jbremer** [comment]
Wouldn't it make sense to simply `git revert` 5fa6705d7af599275193d5eeaad5abf20fcc1fee? Or will this functionality be used later on again - is this a temporary workaround or permanent fix?

**Comment by lunixbochs** [comment]
_(weird I swear I email replied to this)_

This fix is only intended to be temporary, as someone expressed interest in manually setting EFLAGS from hooks.

I think the correct solution might actually be to trampoline Unicorn stop/start when setting EFLAGS (assuming that works), and honestly it will have better performance than inserting a few extra instructions for every single hooked instruction anyway.

**Comment by lunixbochs** [comment]
temp - modifying eflags is useful I hear.

different thought - isn't it likely way less expensive to stop/start trampoline unicorn to set eflags than to add code to every traced instruction? does tcg allow for that here?

**Comment by zaddach** [comment]
I don't know too much about the eflags handling for x86, in ARM it's much
easier. Probably it's a better idea to exit the CPU loop and re-enter it
when EFLAGS registers have been changed. In this case you can simply revert
my earlier patch ...

**Comment by aquynh** [comment]
i merged this, and commented out function restore_eflags() for now. we still need to find out how to sync EFLAGS for callbacks, which was why restore_eflags() was added.

@zachriggle: now the testcase #501 still fails here. are you sure it passes with this PR?

**Comment by lunixbochs** [comment]
> we still need to find out how to sync EFLAGS for callbacks
does #512 not fix this?

**Pull request merged**
