### PR TITLE
fix macro/struct redefinition from winsock2.h

### PR DESCRIPTION
**Pull request by HyperSine**
A new fix for issue #1214. No new macro is introduced this time. 

I have to say it is hard to decide which internal header file `gettimeofday()` moves to. But I found `gettimeofday()` is called at only one place, so I choose to inline it manually. 

BTW, I also fixed a very old issue #635. Just merge code from upstream.

### CODE REVIEW

**Comment by chenhuitao** [comment]
@HyperSine I think that keeping the original getttimeofday() is better, _ftime() works. Just removing the line which includes winsock2.h.

**Comment by HyperSine** [comment]
@chenhuitao 
No, it won't fix any problems. `gentimeofday()` requires `struct timeval` which is [defined in `<winsock.h>`](https://docs.microsoft.com/en-us/windows/win32/api/winsock/ns-winsock-timeval). 

So, if you want to keep the original `gettimeofday()` you must include `<winsock.h>` or `<winsock2.h>` in `<unicorn/platform.h>`. You can't remove `#include <winsock2.h>`. Otherwise, it would break.

**Comment by chenhuitao** [comment]
@HyperSine Thanks for your reply. I think that `<windows.h>` includes the `<winsock.h>` or `<winsock2.h>`, so that we do not need the `<winsock2.h>` in `<unicorn/unicorn.h>`, just remove it to avoid the [winsock2.h-windows.h-conflict problem](https://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h). If someone includes `<winsock.h>` or `<winsock2.h>`  in his code, he should resolve the conflict by himself.

**Comment by HyperSine** [comment]
@chenhuitao 
Yes, `<windows.h>` includes `<winsock.h>` except `<winsock2.h>`. However, `msvc/unicorn/*/*.vcxproj` have `WIN32_LEAN_AND_MEAN` defined. So `<winsock.h>` is stripped from `<windows.h>`. If you remove `#include <winsock2.h>`, neither `<winsock.h>` nor `<winsock2.h>` will be included and unicorn would have compile failure.

**Comment by chenhuitao** [comment]
@HyperSine 
You are right. I missed the macro `WIN32_LEAN_AND_MEAN`.
This [winsock2.h-windows.h-conflict problem](https://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h) is MS's, not unicorn's.
BTW, users add this macro or include the `<winsock2.h>` before the `<windows.h>` in their code is another solution.

**Comment by wtdcode** [comment]
Interesting. Waiting for investigation. #1217

**Comment by wtdcode** [comment]
Manually fixed in 81942e9

**Pull request closed without merging**
