### PR TITLE
patch multiple UC_HOOK_MEM callbacks for unaligned access

### PR DESCRIPTION
**Pull request by Michael-c0de**
The issue https://github.com/unicorn-engine/unicorn/issues/1041 has not been fully resolved，fixed this bug to prevent unaligned accesses from triggering extra callbacks.

### CODE REVIEW

**Comment by wtdcode** [comment]
Do you have a test case for this?

**Comment by Michael-c0de** [comment]
> Do you have a test case for this?
```
#include <unicorn/unicorn.h>

void hook_mem(uc_engine *uc, uc_mem_type type,
    uint64_t address, int size, int64_t value, void *user_data)
{
    printf("%s %p %d\n", (type == UC_MEM_WRITE) ? "write" : "read ", address, size);
}

int main(int argc, char **argv)
{
    const uint8_t code[] = {
        "\x48\x8b\x00"  //  mov         rax,qword ptr [rax]  
        "\x48\x89\x01"  //   mov         qword ptr [rcx],rax  
        "\xcc"
    };

    uc_engine *uc;
    uc_open(UC_ARCH_X86, UC_MODE_64, &uc);
    uc_mem_map(uc, 0, 0x10000, UC_PROT_ALL);
    uc_mem_write(uc, 0, code, sizeof(code) - 1);

    uc_hook hh;
    uc_hook_add(uc, &hh, UC_HOOK_MEM_READ | UC_HOOK_MEM_WRITE, hook_mem, NULL, 1, 0);

    const uint64_t addr = 0x1fff;
    uc_reg_write(uc, UC_X86_REG_RAX, &addr);
    uc_reg_write(uc, UC_X86_REG_RCX, &addr);
    uc_emu_start(uc, 0, sizeof(code) - 1, 0, 2);

    return 0;
}

```

before patch
```
read  0x1fff 8
read  0x1ff8 8
read  0x2000 8
write 0x1fff 8
```

after patch
```
read  0x1fff 8
write 0x1fff 8
```

**Comment by wtdcode** [comment]
> > Do you have a test case for this?
> 
> ```
> #include <unicorn/unicorn.h>
> 
> void hook_mem(uc_engine *uc, uc_mem_type type,
>     uint64_t address, int size, int64_t value, void *user_data)
> {
>     printf("%s %p %d\n", (type == UC_MEM_WRITE) ? "write" : "read ", address, size);
> }
> 
> int main(int argc, char **argv)
> {
>     const uint8_t code[] = {
>         "\x48\x8b\x00"  //  mov         rax,qword ptr [rax]  
>         "\x48\x89\x01"  //   mov         qword ptr [rcx],rax  
>         "\xcc"
>     };
> 
>     uc_engine *uc;
>     uc_open(UC_ARCH_X86, UC_MODE_64, &uc);
>     uc_mem_map(uc, 0, 0x10000, UC_PROT_ALL);
>     uc_mem_write(uc, 0, code, sizeof(code) - 1);
> 
>     uc_hook hh;
>     uc_hook_add(uc, &hh, UC_HOOK_MEM_READ | UC_HOOK_MEM_WRITE, hook_mem, NULL, 1, 0);
> 
>     const uint64_t addr = 0x1fff;
>     uc_reg_write(uc, UC_X86_REG_RAX, &addr);
>     uc_reg_write(uc, UC_X86_REG_RCX, &addr);
>     uc_emu_start(uc, 0, sizeof(code) - 1, 0, 2);
> 
>     return 0;
> }
> ```
> 
> before patch
> 
> ```
> read  0x1fff 8
> read  0x1ff8 8
> read  0x2000 8
> write 0x1fff 8
> ```
> 
> after patch
> 
> ```
> read  0x1fff 8
> write 0x1fff 8
> ```

Cool, could you add this to `tests/unit/test_x86.c`? This ensures that your use cases won't be broken in our futures releases.

**Comment by wtdcode** [comment]
No worry for CI. Github Action is buggy at this moment.

**Comment by wtdcode** [comment]
Sorry for late, I updated your branch and let's wait for CI.

**Comment by wtdcode** [comment]
Thanks!

**Pull request merged**
