### PR TITLE
Small improvements to align with hapstone (Haskell bindings for Capstone)

### PR DESCRIPTION
**Pull request by adrianherrera**
`Enum`s now derive `Bounded` and I've made use of `Applicative` in the Utils module.

### CODE REVIEW

**Comment by ibabushkin** [comment]
Hapstone author here. Do you plan to write tests for your bindings? I did, using `quickcheck` and `hspec`, and it caught some bugs arising due to incompatibilities on `c2hs`' side. That's what the bounded instances are originally for (though they are useful elsewhere as well), because you can write simple `Arbitrary` instances like this:
```Haskell
instance Arbitrary CsArch where
    arbitrary = elements [minBound..maxBound]
```
So if you need tests, maybe hapstone's test suite is worth a look ;)

Cheers.

**Comment by adrianherrera** [comment]
I did get the idea to write some tests after looking at hapstone. I will
look into it. I'm hoping there aren't any incompatibles with c2hs though!

Thanks for the comment.

**Comment by ibabushkin** [comment]
The main issue with `c2hs` was the fact that it doesn't support C11, which capstone uses (most notably anonymous unions, which leads to problems with the `{#alignof#}`, `{#sizeof#}`, `{#offsetof#}` `{#get#}`, `{#set#}`.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by adrianherrera** [comment]
@ibabushkin thanks for the heads up! Fortunately, there weren't any C11 features (that I was aware of anyway) in Unicorn that I had to verify.

**Comment by lunixbochs** [comment]
Unicorn isn't even C99

**Pull request merged**
