### PR TITLE
fix broken build

### PR DESCRIPTION
**Pull request by stephengroat**
fixes broken build

### CODE REVIEW

**Comment by aquynh** [comment]
why dont we have Travis, but only Appveyor now?

**Comment by aquynh** [comment]
btw, i think would be nice to have Appveyor to keep a build (artifact?), and publish it, so users can easily get the latest Windows binary. how can we do this?

**Comment by stephengroat** [comment]
@aquynh travis-ci.org is kinda deprecated, i'd try moving to travis-ci.com and enabling the new travis ci app https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by stephengroat** [comment]
i'll try to make a separate pr for appveyor build artifacts

**Comment by stephengroat** [comment]
seems to be working now

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
