### PR TITLE
Makefile Updated

### PR DESCRIPTION
**Pull request by jcalabres**
The Java binding needs some changes in order to work correctly with the new Java versions.

### CODE REVIEW

**Comment by aquynh** [comment]
does this affect the older version of Java?

@cseagle please ack.

**Comment by jcalabres** [comment]
Hello, I was having problems with the makefile provided. As the new versions are not using javah anymore for generating the headers files, javac with -h it's needed. In addition, in order to use extensions in new Java versions, you need to specify the classpath. I'm not sure but, it's working for me using classpath in both, javac and java. 
So, yes, this is affecting old versions of Java, but without these kinds of changes, ppl cannot compile the Java Binding (no ghidra extensions :( )
Thank you!

**Comment by aquynh** [comment]
i see. is there anyway to support older version too, so we dont sacrifice compatibility?

**Comment by wtdcode** [comment]
Link to #1217 #1449.

**Comment by wtdcode** [comment]
Merged in 3dfec280c765384c5536126d103c6781633f29a2.

**Pull request closed without merging**
