### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by LilyWangLL**
Unicorn is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for unicorn and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build unicorn, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here](https://github.com/microsoft/vcpkg/blob/master/ports/unicorn/portfile.cmake) is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

### CODE REVIEW

**Comment by wtdcode** [comment]
Hello, thanks for vcpkg’s efforts!

So there is nothing Unciorn has to do for vcpkg? btw, pr shall go to dev branch.

**Comment by mrexodia** [comment]
Why not use the CMakeLists.txt instead of the VS solution so it's cross platform? Or maybe I misunderstand

```
vcpkg_build_msbuild(
    PROJECT_PATH "${SOURCE_PATH}/msvc/unicorn.sln"
    PLATFORM "${UNICORN_PLATFORM}"
)
```

**Comment by LilyWangLL** [comment]
> Why not use the CMakeLists.txt instead of the VS solution so it's cross platform? Or maybe I misunderstand
> 
> ```
> vcpkg_build_msbuild(
>     PROJECT_PATH "${SOURCE_PATH}/msvc/unicorn.sln"
>     PLATFORM "${UNICORN_PLATFORM}"
> )
> ```

Using CMakeLists.txt instead of VS solution will be fixed by PR https://github.com/microsoft/vcpkg/pull/26101.

**Comment by LilyWangLL** [comment]
> Hello, thanks for vcpkg’s efforts!
> 
> So there is nothing Unciorn has to do for vcpkg? btw, pr shall go to dev branch.

There is nothing to do, please merge this PR when everything is OK. I have changed the base branch from master to dev, is this correct?

**Comment by wtdcode** [comment]
Thanks!

**Pull request merged**
