### PR TITLE
flush tlb for each emulation issue #552

### PR DESCRIPTION
**Pull request by 5lipper**

### CODE REVIEW

**Comment by lunixbochs** [comment]
what are the performance implications of this if I'm rapidly stopping/restarting the emulator?

**Comment by aquynh** [comment]
How about flushing whenever we unmap memory?

**Comment by 5lipper** [comment]
```c
void memory_unmap(struct uc_struct *uc, MemoryRegion *mr)
{
    int i;
    target_ulong addr;
    Object *obj;

    // Make sure all pages associated with the MemoryRegion are flushed
    // Only need to do this if we are in a running state
    if (uc->current_cpu) {
        for (addr = mr->addr; addr < mr->end; addr += uc->target_page_size) {
           tlb_flush_page(uc->current_cpu, addr);
        }
    }
```
Only flushing the unmapped pages is a better idea, but how can we get
the assigned cpu if we are not in a running state?

**Comment by aquynh** [comment]
in the case the emulation is not running, we can fall back to the first solution: flush all the cache inside uc_emu_start().

**Comment by lunixbochs** [comment]
why even use `uc->current_cpu`? why not just `CPU_FOREACH` and flush 'em all? (I don't think a single uc will or should use multiple cpus anyway)

**Comment by 5lipper** [comment]
@lunixbochs I did that in a commit before this one, but it's not merged. Then I think @aquynh is talking about flushing all cache when it's not running. I don't know if a single uc can only use one cpu :(

**Comment by lunixbochs** [comment]
I really don't like the idea of flushing all cache when we know only a couple of pages need to be flushed - that's not efficient :)

**Comment by lunixbochs** [comment]
diff --git a/qemu/memory.c b/qemu/memory.c
    index 3ab5c7a..a0c0b3e 100644
    --- a/qemu/memory.c
    +++ b/qemu/memory.c
    @@ -71,12 +71,13 @@ void memory_unmap(struct uc_struct *uc, MemoryRegion *mr)
         int i;
         target_ulong addr;
         Object *obj;
    +    CPUState *cpu;

         // Make sure all pages associated with the MemoryRegion are flushed
         // Only need to do this if we are in a running state
    -    if (uc->current_cpu) {
    +    CPU_FOREACH(cpu) {
             for (addr = mr->addr; addr < mr->end; addr += uc->target_page_size) {
    -           tlb_flush_page(uc->current_cpu, addr);
    +           tlb_flush_page(cpu, addr);
             }
         }
         mr->enabled = false;

**Pull request closed without merging**
