### PR TITLE
Fix compile if HAS_ARM is defined but HAS_ARM_EB isn't

### PR DESCRIPTION
**Pull request by bpfoley**
This allows us to build LE-only ARM unicorn variants

### CODE REVIEW

**Comment by aquynh** [comment]
which command did you use to build?

**Comment by bpfoley** [comment]
I did this as part of some custom build scripts to build Unicorn as a part of a library where I only wanted a Little Endian ARM support and no other platform. To do that I used -DUNICORN_HAS_ARM but not -DUNICORN_HAS_ARMEB.

This seems like a fairly reasonable thing that others may want to do given that ARMEB is relatively unusual.

**Comment by aquynh** [comment]
you can put that into this PR too, so it will be useful for others?

**Comment by bpfoley** [comment]
I'm not sure they're that useful. The scripts are actually Google-internal [bazel](https://bazel.build/) build rules. They're good enough for what we need, but aren't configurable enough for general purpose use.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
