### PR TITLE
Small correction in README

### PR DESCRIPTION
**Pull request by adolphenom**
- A little correction in the license. It was "open source" rather than "free software". I know it's not very important for some people, but other people care about that.
- Linked COPYING file to the "GPL license" at the end of the README.

### CODE REVIEW

**Comment by aquynh** [comment]
why do people want "free software", but not "open source"?

thanks.

**Comment by adolphenom** [comment]
Hi, thank you for answer to my PR @aquynh :)

It's not what people wants but what it's the correct definition of the license. GNU GPL (1, 2 or 3) is a Free Software license, not an Open Source license. An Open Source license is, e.g., MIT, Apache v2.0, BSD or BSD-like.

That's the only reason I did this PR.

**Comment by aquynh** [comment]
cool, i never paid attention about this detail!

merged, thanks.

**Comment by adolphenom** [comment]
Thank you very much, @aquynh :D

**Comment by aquynh** [comment]
thanks for your contribution!

**Pull request merged**
