### PR TITLE
two more testcases

### PR DESCRIPTION
**Pull request by eqv**

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
on OSX, these 2 testcases never have any problems. what is your environment?

**Comment by eqv** [comment]
Ubuntu, the problem seems to be a memcpy with overlapping ranges which is undefined behviour. It's quite likely that your implementation of memcpy does something different from the one on my system. However if you run the testcase in valgrind you should be able to see the overlapping memcpy no matter how it is implemented.

**Comment by lunixbochs** [comment]
Ooh, I had some problems with inconsistent crashes on Linux I haven't looked into yet. This might be related.

**Pull request merged**
