### PR TITLE
Add arm ite blocks samples from #853

### PR DESCRIPTION
**Pull request by wtdcode**
Add the sample from #853 to sample-arm.c.

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by crass** [comment]
This is causing the make test to fail.

```
cd .. && python const_generator.py python  
make[2]: Leaving directory '/home/ubuntu-budgie/unicorn.git/bindings/python'
LD_PRELOAD=librt.so LD_LIBRARY_PATH=../ DYLD_LIBRARY_PATH=../ ../samples/sample_
arm > sample_arm.c.txt
LD_PRELOAD=librt.so LD_LIBRARY_PATH=../ DYLD_LIBRARY_PATH=../ python python/samp
le_arm.py > sample_arm.py.txt
diff -u sample_arm.c.txt sample_arm.py.txt 
--- sample_arm.c.txt    2021-08-19 03:04:24.443138456 +0000
+++ sample_arm.py.txt   2021-08-19 03:04:24.587139604 +0000
@@ -10,13 +10,3 @@
 >>> Tracing instruction at 0x10000, instruction size = 0x2
 >>> Emulation done. Below is the CPU context
 >>> SP = 0x1228
-==========================
-Emulate a THUMB ITE block as a whole or per instruction.
-Running the entire binary.
->>> R2: 104
->>> R3: 1
-
-Running the binary one instruction at a time.
->>> R2: 104
->>> R3: 1
-
make[1]: *** [Makefile:46: sample_arm.py.test] Error 1
```

**Comment by wtdcode** [comment]
I’m afraid that test isn’t properly maintained for a long time. And samples are not designed for testing purpose.
________________________________

**Comment by crass** [comment]
I deleted my previous comment before I had seen your reply because I realized that the problem wasn't this commit but a previous one. However, if samples aren't designed for testing purposes, then why are they included in `make test`?

**Comment by wtdcode** [comment]
As explained just now, the ‘make test’ is not maintained (the tests are really a big mess, see tests/ directory for details). It shall work in uc2. Link to #1217.
________________________________

**Pull request merged**
