### PR TITLE
Add test case for unicorn-engine/unicorn#499

### PR DESCRIPTION
**Pull request by zachriggle**
This currently fails because of #499

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
this is not important, but why did you set RIP? that is not necessary, because later you start emulation, which will reset the RIP

**Comment by aquynh** [comment]
so basically on physical machine the reserved flag (bit 1) is turned on, but Unicorn ignores this flag?

**Comment by aquynh** [comment]
what is the value of EFLAGS with this XOR instruction in Qemu?

**Comment by zachriggle** [comment]
The results within `qemu-user` are identical to the native results.  See https://github.com/unicorn-engine/unicorn/issues/499#issuecomment-204630258

**Comment by zachriggle** [comment]
@aquynh: RIP is set because of how I initialize *all* registers in my emulation code from the actual machine state.  Easier to just set everything than have special cases to not-set-`$PC`-because-it'll-be-overwritten.

**Pull request merged**
