### PR TITLE
add batched reg access

### PR DESCRIPTION
**Pull request by lunixbochs**
add reg_read_batch and reg_write_batch API

this improves Usercorn's overall execution speed when doing a register trace by over 2x

related to #8

one of the reasons I want selective register access instead of all-at-once, is the syscall/function call ABI only requires a small subset of registers

### CODE REVIEW

**Comment by aquynh** [comment]
apparently this still has some issues with Travis, would you take a look?

**Comment by lunixbochs** [comment]
right, I added `for (int i = 0` reflexively: `‘for’ loop initial declarations are only allowed in C99 mode`

**Comment by lunixbochs** [comment]
travis passes now

**Comment by trufae** [comment]
didnt tested, but this thing will be great for r2 integration :)

**Comment by aquynh** [comment]
this looks good! will you add some sample code (under samples/) to demonstrate these new APIs?

**Comment by lunixbochs** [comment]
just pushed a sample

**Comment by zachriggle** [comment]
Looks nice!  Can haz Python bindings? :D

**Comment by aquynh** [comment]
merged, thanks!

@zachriggle, i leave that Python binding work to you :-)

**Pull request merged**
