### PR TITLE
cmake: fix build if workdir is outside of CMAKE_BINARY_DIR

### PR DESCRIPTION
**Pull request by Johnnynator**
this e.g. happens if you would try to compile this like this:

cmake -B build
cmake --build build --config Release

@scribam Should fix the remaining CI failures of https://github.com/Vita3K/Vita3K/pull/727

### CODE REVIEW

**Comment by scribam** [comment]
@Johnnynator 
:thinking: Have you tried it? It does not work for me locally :confused: 
But I think instead it is necessary to set a `WORKING_DIRECTORY` for this command `COMMAND sh ${CMAKE_CURRENT_SOURCE_DIR}/qemu/configure` to fix the failures.

**Comment by Johnnynator** [comment]
Mh... I did try, maybe smth of a different build leaked in. But in that case it should be needed for both.

**Comment by Johnnynator** [comment]
This doesn't make any sense why the previous change did work for me. The create_config script is totally workdir independent and just takes stdin/stdout, cmake itself already works with the correct paths.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
