### PR TITLE
Migration for Travis-CI

### PR DESCRIPTION
**Pull request by chfl4gs**
make test disabled for msys2/MinGW for now.

### CODE REVIEW

**Comment by aquynh** [comment]
this makes Travis support Windows, so we may remove Appveyor CI later. @stephengroat do you have any comments?

**Comment by stephengroat** [comment]
this seems to remove msys2 support

is that the idea?

**Comment by chfl4gs** [comment]
msys2 support is still there. However make test is not implemented as there is some issue with shared library loading.

**Comment by chfl4gs** [comment]
Test run results are here.
https://travis-ci.com/chfl4gs/unicorn/builds/143668320

**Comment by chfl4gs** [comment]
make test produces error as shown in https://travis-ci.com/chfl4gs/unicorn/builds/143214405#L1138

**Comment by aquynh** [comment]
nice, will we have msys support soon?

**Pull request closed without merging**
