### PR TITLE
test appveyor artifacts

### PR DESCRIPTION
**Pull request by stephengroat**
@aquynh this pushes all of the windows `dll`s into build artifacts. Is there anything else you're thinking of?

### CODE REVIEW

**Comment by aquynh** [comment]
that sounds good! but this build is for Cygwin/MingW, so we need to include dependency DLLs as well?

ideally we should build MSVC to have native DLLs, but i am not sure if that is possible?

**Comment by stephengroat** [comment]
@aquynh for cygwin, this is a more complicated issue. There was a project that tried to deal with it (https://stackoverflow.com/questions/1981043/running-an-application-compiled-in-cygwin-without-having-cygwin-installed), but it's pretty much defunct now.
for msys2, it really requires a lot of modification to the system `PATH` to make it work (https://stackoverflow.com/questions/46857894/running-a-gtk-application-built-with-msys2-by-just-double-clicking-it)

i don't know enough about the msvc build process to really comment too much, sorry!

**Comment by aquynh** [comment]
our last release 1.0.1 (for ex https://github.com/unicorn-engine/unicorn/releases/download/1.0.1/unicorn-1.0.1-win64.zip) built with Cygwin, and we included libwinpthread-1.dll & libgcc_s_seh-1.dll, which also seems to work in Python binding for Windows. so these 2 files are enough as dependency?

**Comment by stephengroat** [comment]
@aquynh that list seems a bit light. i'm pretty sure all cygwin dlls rely on at least `cygwin1.dll`

[after running `ldd` on `cygunicorn.dll`](https://ci.appveyor.com/project/aquynh/unicorn/builds/26668449/job/l9l75uh3e4f3de26#L1519), this is what is got:

```
if defined CYG_ROOT (%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ldd cygunicorn.dll")
	ntdll.dll => /cygdrive/c/windows/SYSTEM32/ntdll.dll (0x7ffacc760000)
	KERNEL32.DLL => /cygdrive/c/windows/system32/KERNEL32.DLL (0x7ffaca610000)
	KERNELBASE.dll => /cygdrive/c/windows/system32/KERNELBASE.dll (0x7ffac9ac0000)
	cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
	cyggcc_s-seh-1.dll => /usr/bin/cyggcc_s-seh-1.dll (0x3fdd70000)
	advapi32.dll => /cygdrive/c/windows/system32/advapi32.dll (0x7ffaca140000)
	msvcrt.dll => /cygdrive/c/windows/system32/msvcrt.dll (0x7ffacac60000)
	sechost.dll => /cygdrive/c/windows/SYSTEM32/sechost.dll (0x7ffaca3c0000)
	RPCRT4.dll => /cygdrive/c/windows/system32/RPCRT4.dll (0x7ffacc460000)
	SspiCli.dll => /cygdrive/c/windows/system32/SspiCli.dll (0x7ffac9be0000)
	CRYPTBASE.DLL => /cygdrive/c/windows/SYSTEM32/CRYPTBASE.DLL (0x7ffac9700000)
	bcryptPrimitives.dll => /cygdrive/c/windows/SYSTEM32/bcryptPrimitives.dll (0x7ffac9690000)
```

personally, i don't think including any of these system dlls makes sense. but if you want to include some of them (like everything in `/usr`), could easily add those to the appveyor push)

**Comment by aquynh** [comment]
@rhelmot i think the last Pypi package for v1.0.1 on Windows works well with just few Cygwin DLLs?

**Comment by aquynh** [comment]
> @rhelmot i think the last Pypi package for v1.0.1 on Windows works well with just few Cygwin DLLs?

no i think that was built with Msys, not Cygwin.

**Comment by stephengroat** [comment]
@aquynh [output for `ntldd` for `msys2`](https://ci.appveyor.com/project/aquynh/unicorn/builds/26671850/job/huymlc04ja6ep4px#L1040)

```
if defined MSYSTEM (%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ntldd unicorn.dll")
	KERNEL32.dll => C:\windows\SYSTEM32\KERNEL32.dll (0x0000000002660000)
	msvcrt.dll => C:\windows\SYSTEM32\msvcrt.dll (0x0000000002660000)
	libgcc_s_seh-1.dll => C:\msys64\mingw64\bin\libgcc_s_seh-1.dll (0x0000000000300000)
```

**Comment by aquynh** [comment]
@rhelmot do you have any comments?

**Comment by rhelmot** [comment]
I don't have any comments. any way we can configure the package to work works.

**Comment by aquynh** [comment]
I asked because this is also how we package for Pypi Windows. Last time did
you build with msys? If so, you may have the same problem with this issue
now?

**Comment by rhelmot** [comment]
I have not once in my life successfully built unicorn for windows myself. Every time I package it I just use the dlls you build.

**Comment by aquynh** [comment]
i will just merge this now, and later we will move to cmake & native msvc, thanks

**Comment by Waterman178** [comment]
mark

**Pull request merged**
