### PR TITLE
Emu stop in hook overrun

### PR DESCRIPTION
**Pull request by xorstream**
Added test for uc_emu_stop() in code hook not always stopping the emu at the current instruction.

In the added code it should stop when executing the instruction at the address 0x100008 but you can see it goes on to execute the instrucion at 0x10000C before then stopping with a PC value being 0x10000C.

### CODE REVIEW

**Comment by aquynh** [comment]
can you please add `emu_stop_in_hook_overrun` to `.gitignore` as well?

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
fixed, please confirm.

still need to fix this issue for other archs (x86 & mips already fixed).

**Comment by xorstream** [comment]
Fix works for me in the test code and my more complex external project. (Both are MIPS)

**Pull request merged**
