### PR TITLE
Multiply instead of shifting negative values

### PR DESCRIPTION
**Pull request by catenacyber**
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10419

### CODE REVIEW

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10421

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10422

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10425

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10427

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10428

**Comment by Coldzer0** [comment]
Hello @catenacyber 
i see that you are active on fixing bugs

so can you please give some of your time to check this issue
https://github.com/unicorn-engine/unicorn/issues/820
i'm working on a PE Emulator and i almost finish a beta version 
but this issue make a real challenge when it come to self modify code  

thanks so much

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10429

**Comment by Coldzer0** [comment]
@catenacyber 
thanks in advance 

and no it has nothing to do with undefined shifts , i'm sorry i comment in this pr , but i try to find a contact to you through github but i didn't find any so i posted here

sorry again for that .

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10430

**Comment by catenacyber** [comment]
@Coldzer0 you can mail at contact@catenacyber.fr

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10431

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10436

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10444 should be fixed as well

**Comment by catenacyber** [comment]
and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10449

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10456

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10460

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10458

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10426

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10452 should be fixed as well

**Comment by wtdcode** [comment]
Closed due to uc2 beta release.

**Pull request closed without merging**
