### PR TITLE
Test for stack hooking.

### PR DESCRIPTION
**Pull request by univm**
If address < 0x0030000 the hook isn't called.

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by univm** [comment]
Ah, it appears the problem is if you don't specify begin > end the values are not initialized and seems to make it not work.

I believe if these values are not specified, they should be initialized to default begin > end.

**Comment by aquynh** [comment]
you can send a pull request to do this.

**Comment by aquynh** [comment]
it is better if we can enforce these parameters so they must be always present.

**Comment by lunixbochs** [comment]
You can't enforce missing arguments in C.

**Pull request merged**
