### PR TITLE
A simple API Doc in chinese

### PR DESCRIPTION
**Pull request by kabeor**
A simple API Doc in chinese

### CODE REVIEW

**Comment by aquynh** [comment]
nice, but how about putting all the PNG files in here (rather than having elsewhere)?

**Comment by kabeor** [comment]
> nice, but how about putting all the PNG files in here (rather than having elsewhere)?

Ok, I'll transfer the picture now

**Comment by kabeor** [comment]
> 很好，但是如何将所有PNG文件放在这里（而不是放在其他地方）？

I find it easier to upload a PDF，so I sent that

**Comment by aquynh** [comment]
i still recommend text file, but not PDF, because you or others can correct typo/mistakes, or update it in the future.

**Comment by kabeor** [comment]
> i still recommend text file, but not PDF, because you or others can correct typo/mistakes, or update it in the future.

ok, I have finished it.

**Comment by aquynh** [comment]
please also add  a link to https://github.com/unicorn-engine/unicorn/blob/master/docs/README.md

**Comment by kabeor** [comment]
> please also add a link to https://github.com/unicorn-engine/unicorn/blob/master/docs/README.md

it's done

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
