### PR TITLE
Create mem_map_0x100000000.c

### PR DESCRIPTION
**Pull request by horsicq**
UC_ERR_MAP Error #616

### CODE REVIEW

**Comment by aquynh** [comment]
dont you add this to Makefile?

**Comment by horsicq** [comment]
Done.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
what is your env? here is what i got on Mac with this testcase:

```
$ ./mem_map_0x100000000
mem_map_0x100000000.c
Success.
```

**Comment by horsicq** [comment]
Windows 7 X64 
MinGW 4.9 X32

I have tested it on Ubuntu16.04 X64. It works perfect.

**Comment by horsicq** [comment]
It's on 32bits Systems only because ram_addr_t in MemoryRegion is dword.

**Comment by cseagle** [comment]
This is totally related to issue https://github.com/unicorn-engine/unicorn/issues/523 and PR https://github.com/unicorn-engine/unicorn/pull/526 which has never been merged

**Comment by horsicq** [comment]
> This is totally related to issue #523 and PR #526 which has never been merged

Thanks.

**Comment by aquynh** [comment]
Chris, i dont forget your PR, but i havent merged that since i think there is a better fix for that issue. will try to get some time to look at it this week.

**Comment by horsicq** [comment]
Another solution - just add CONFIG_XEN_BACKEND to "qemu/Makefile"

**Pull request merged**
