### PR TITLE
Bug fix for java binding of Apple silicon.

### PR DESCRIPTION
**Pull request by zhkl0228**
Because Java also has JIT code, Java binding in Apple M1 does not execute "tb_exec_lock" at the end of execution, which will cause "SIGBUS" exception in the execution of JIT code in Java.

### CODE REVIEW

**Comment by wtdcode** [comment]
I don't think it's the correct way to fix though it might solve your issue for now. Why is java special in this case?

**Comment by zhkl0228** [comment]
The java code will also be converted into local code by jit. When the unicorn execution is completed, if pthread_jit_write_protect is not called, the jit at the java layer will fail to execute.

**Comment by AeonLucid** [comment]
This PR also fixed unicorn crashing in .NET 6 on a M1 Macbook Air. Would be great to get fixed.

**Comment by wtdcode** [comment]
It's quite unclear to me how these fixes work without an M1 test environment. I can review this probably after I get one for debugging.

**Comment by AeonLucid** [comment]
Not stale.

**Comment by wtdcode** [comment]
Applied the correct fix here: 6e97e59f5416e2cd3ad7d476061d9f7dc38eb66c

**Pull request closed without merging**
