### PR TITLE
Fix memory read callback to return a value instead of 0

### PR DESCRIPTION
**Pull request by farmdve**
This changes the order of the callback depending on some situations.

@aquynh 
What do you think?

### CODE REVIEW

**Comment by farmdve** [comment]
@aquynh Are the changes ok?

**Comment by aquynh** [comment]
this sounds ok. will look closer this weekend when i have more time, thanks!

**Comment by aquynh** [comment]
this change modifies the semantics of current UC_HOOK_MEM_READ, in which we no longer get the notification on read event, but only when read is successful. originally, the memory value passed to the callback is *irrelevant*, and should not be referenced during the callback (actually i should not include this parameter for this callback when i designed this API). now with this change, we get the value (since read is successful)

any comments?

**Comment by lunixbochs** [comment]
I like the change. I was previously manually reading the address from unicorn which has way more overhead.

**Comment by aquynh** [comment]
how about this solution: rather than changing the semantics of UC_HOOK_MEM_READ, we add a new hooking type UC_HOOK_MEM_READ_AFTER, which is triggered **after** memory read successes? this requires a new memory event UC_MEM_READ_AFTER, too.

**Comment by aquynh** [comment]
i implemented this as discussed above by adding a new hook type UC_HOOK_MEM_READ_AFTER, and also introduced a new memory access event UC_MEM_READ_AFTER. the commit is https://github.com/unicorn-engine/unicorn/commit/4083b870324a6256242ce266844ff6e7e5bbd7f7. if you see any issues, please report.

**Pull request closed without merging**
