### PR TITLE
Qemu 3.1.0rc2 merging

### PR DESCRIPTION
**Pull request by catenacyber**
This is mostly the work from @lioncash
It fixes some (all ?) the bugs found by oss-fuzz

It is obviously a big change that should be tested
But I guess that this change, bring unicorn to qemu current level, is needed...

### CODE REVIEW

**Comment by aquynh** [comment]
this is amazing!

looks like the last commit breaks compilation? does that come from original Qemu?

**Comment by catenacyber** [comment]
The last commit comes from me.
It was needed for compilation on oss-fuzz docker image where we do not have `CONFIG_ATOMIC64` defined.

On Travis, it does not look like compilation is broken, but tests are. Am I reading it correctly ?

**Comment by catenacyber** [comment]
And it succeeds without commit b25016f ?

**Comment by aquynh** [comment]
Yes seems so.

**Comment by lunixbochs** [comment]
At a glance, looks like X86 IN/OUT instructions and syscalls don’t work

**Comment by aquynh** [comment]
a quick test on Ubuntu 64bit 18.04, and currently some samples break. for example `samples/sampe_x86` enters a loop, and `samples/sample_arm` also fails on uc_emu_start(), like below.

```
$ ./samples/sample_arm
Emulate ARM code
>>> Tracing instruction at 0x10000, instruction size = 0x4
Failed on uc_emu_start() with error returned: 8
>>> Emulation done. Below is the CPU context
>>> R0 = 0x37
>>> R1 = 0x3456
==========================
Emulate THUMB code
>>> Emulation done. Below is the CPU context
>>> SP = 0x1234
```

**Comment by aquynh** [comment]
similar to `sample_arm`, `sample_mips` also fails:

```
$  ./samples/sample_mips
Emulate MIPS code (big-endian)
>>> Tracing instruction at 0x10000, instruction size = 0xf8f8f8f8
Failed on uc_emu_start() with error returned: 8 (Invalid memory fetch (UC_ERR_FETCH_UNMAPPED))
>>> Emulation done. Below is the CPU context
>>> R1 = 0x77df
===========================
Emulate MIPS code (little-endian)
>>> Tracing instruction at 0x10000, instruction size = 0xf8f8f8f8
Failed on uc_emu_start() with error returned: 8 (Invalid memory fetch (UC_ERR_FETCH_UNMAPPED))
>>> Emulation done. Below is the CPU context
>>> R1 = 0x77df
```

**Comment by catenacyber** [comment]
Now `sample_arm` should work again

**Comment by aquynh** [comment]
looks like when syncing with the newer code, those modification we did with 2.1.2 was not properly integrated yet.

**Comment by catenacyber** [comment]
Indeed, so what is the best way to level Qemu in unicorn : merging and running the tests on each commit to see which are the ones who break them ?..

**Comment by mewmew** [comment]
> Now sample_arm should work again

@catenacyber and @aquynh, what is the state of this PR? It seems like the best effort thus far to bring Unicorn closer to sync with Qemu.

Are these a list of things still left to do before this can be merged? And, if it should not be merged, then it would be good to know why, so that other efforts to bring Unicorn up to sync would learn from this massive work.

Cheers,
Robin

**Comment by aquynh** [comment]
some sample code under samples/ still dont work. do you want to contribute
by fixing them first?

**Comment by mewmew** [comment]
> some sample code under samples/ still dont work. do you want to contribute by fixing them first?

Hi @aquynh!

I do not yet have enough insight into either Qemu nor Unicorn to solve these with confidence. However, I can help summarize what test cases are currently failing. Those are as follows:

* bindings test cases (`make -C bindings test`)
   - [ ] `samples/sample_x86.c`: stuck in infinite loop
   - [ ] `samples/sample_arm64eb.c`: Failed on uc_emu_start() with error returned: 21
   - [ ] `samples/sample_mips.c`: segmentation fault when running `python/sample_mips.py`, the C version runs without segfault
   - [ ] `samples/sample_m68k.c`: different output between C and Python (`D3 = 0x0` in C and `D3 = 0x1234` in Python)
* unit test cases (`make -C tests/unit test`)
   - [ ] `test_i386_jump_invalid`: never finishes
   - [ ] `test_x86_64_syscall`: never finishes

# Test results of bindings test cases

## samples/sample_x86.c

```bash
$ du -hs bindings/sample_x86.c.txt
20G	sample_x86.c.txt
```

## samples/sample_arm64eb.c

```diff
diff -u sample_arm64eb.c.txt sample_arm64eb.py.txt
--- sample_arm64eb.c.txt	2019-11-22 19:12:50.509924403 -0500
+++ sample_arm64eb.py.txt	2019-11-22 19:12:50.679924412 -0500
@@ -1,6 +1,3 @@
 Emulate ARM64 Big-Endian code
 >>> Tracing instruction at 0x10000, instruction size = 0x4
-Failed on uc_emu_start() with error returned: 21
->>> Emulation done. Below is the CPU context
->>> As big endian, X15 should be 0x12:
->>> X15 = 0x33
+ERROR: Unhandled CPU exception (UC_ERR_EXCEPTION)
```

## samples/sample_mips.c

```bash
LD_PRELOAD=librt.so LD_LIBRARY_PATH=../ DYLD_LIBRARY_PATH=../ ../samples/sample_mips > sample_mips.c.txt
LD_PRELOAD=librt.so LD_LIBRARY_PATH=../ DYLD_LIBRARY_PATH=../ python python/sample_mips.py > sample_mips.py.txt
/bin/sh: line 1: 10910 Segmentation fault      (core dumped) LD_PRELOAD=librt.so LD_LIBRARY_PATH=../ DYLD_LIBRARY_PATH=../ python python/sample_mips.py > sample_mips.py.txt
```

## samples/sample_m68k.c

```diff
diff -u sample_m68k.c.txt sample_m68k.py.txt
--- sample_m68k.c.txt	2019-11-22 19:11:42.749920764 -0500
+++ sample_m68k.py.txt	2019-11-22 19:11:42.926587440 -0500
@@ -3,7 +3,7 @@
 >>> A0 = 0x0		>>> D0 = 0x0
 >>> A1 = 0x0		>>> D1 = 0x0
 >>> A2 = 0x0		>>> D2 = 0x0
->>> A3 = 0x0		>>> D3 = 0x0
+>>> A3 = 0x0		>>> D3 = 0x1234
 >>> A4 = 0x0		>>> D4 = 0x0
 >>> A5 = 0x0		>>> D5 = 0x0
 >>> A6 = 0x0		>>> D6 = 0x0
make[1]: *** [Makefile:46: sample_m68k.py.test] Error 1
```

# Uncommented unit test cases (as they never finish)

```diff
diff --git a/tests/unit/test_x86.c b/tests/unit/test_x86.c
index f890a26f..a7eac895 100644
--- a/tests/unit/test_x86.c
+++ b/tests/unit/test_x86.c
@@ -485,7 +485,6 @@ static void test_i386_jump_invalid(void **state)
     uc_assert_success(uc_close(uc));
 }
 
 /******************************************************************************/
 
 static void hook_mem64(uc_engine *uc, uc_mem_type type,
@@ -813,11 +812,11 @@ int main(void) {
         cmocka_unit_test(test_i386_loop),
         cmocka_unit_test(test_i386_invalid_mem_read),
         cmocka_unit_test(test_i386_invalid_mem_write),
-        cmocka_unit_test(test_i386_jump_invalid),
+        //cmocka_unit_test(test_i386_jump_invalid),
         cmocka_unit_test(test_i386_reg_save),
 
         cmocka_unit_test(test_x86_64),
-        cmocka_unit_test(test_x86_64_syscall),
+        //cmocka_unit_test(test_x86_64_syscall),
 
         cmocka_unit_test(test_x86_16),
 ```

# Update to `Makefile` of bindings test cases (to selectively disable/enable test cases

```diff
diff --git a/bindings/Makefile b/bindings/Makefile
index 296b44f3..97299866 100644
--- a/bindings/Makefile
+++ b/bindings/Makefile
@@ -2,7 +2,7 @@
 # By Nguyen Anh Quynh & Dang Hoang Vu, 2015
 DIFF = diff
 
-SAMPLE_SOURCE = $(wildcard ../samples/*.c)
+SAMPLE_SOURCE = $(filter-out ../samples/sample_x86.c ../samples/sample_arm64eb.c ../samples/sample_mips.c ../samples/sample_m68k.c, $(wildcard ../samples/*.c))
 SAMPLE = $(SAMPLE_SOURCE:../samples/%.c=%)
 SAMPLE := $(SAMPLE:mem_apis=)
 SAMPLE := $(SAMPLE:sample_batch_reg=)
```

**Comment by catenacyber** [comment]
My guess is that the best thing is to cherry-pick qemu commits one by one, fox conflicts and see if the tests are still ok.
So that means a lot of work as there are a lots of commits and qemu commits may break some unicorn requirements such as thread-safeness.

**Comment by wtdcode** [comment]
Closed due to uc2 beta release.

**Pull request closed without merging**
