### PR TITLE
Final tweaks to MSVC build

### PR DESCRIPTION
**Pull request by rhelmot**
- Quote filepaths in post-build scripts so it can work for dumbasses like me with spaces in their usernames
- Update README with more maintenance advice

After this we can release 1.0.2.

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

@stephengroat, can we run "msbuild" in Appveyor, and even better, keep its artifacts?

**Comment by stephengroat** [comment]
@aquynh looks likes it's already being run

do you know what artifacts you want to keep? i'm currently keeping unicorn.dll https://github.com/unicorn-engine/unicorn/blob/master/.appveyor.yml#L65

**Comment by aquynh** [comment]
so this unicorn.dll already natively built with msvc. 

the goal is that users can download & use the artifacts to build their own tools on Windows (without having to build latest unicorn themselves).

do we already provide the link to the artifacts in our docs yet?

**Comment by stephengroat** [comment]
pr specific or based off of last successful master build?

https://ci.appveyor.com/api/projects/aquynh/unicorn/artifacts/unicorn.dll?branch=master&job=CC%3Dmsvc

is a permalink to the unicorn dll for the last successful job on master for msvc

**Pull request merged**
