### PR TITLE
Travis-CI Migration

### PR DESCRIPTION
**Pull request by chfl4gs**
- Test on msys2 added.
- osx brew failed due to issue #1228

### CODE REVIEW

**Comment by chfl4gs** [comment]
Build details can be found [here](https://travis-ci.com/github/chfl4gs/unicorn/builds/159823222)

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
@stephengroat this enables Windows build with Travis. do you think we should remove Appveyor?

**Comment by stephengroat** [comment]
don't see any reason to keep it

**Pull request merged**
