### PR TITLE
reg_read and reg_write now work with registers W0 through W30 in Aarch64

### PR DESCRIPTION
**Pull request by eltongo**
Based on issue #714, I added the ability to read and write registers W0 through W30 for Aarch64 using the reg_read and reg_write functions.

### CODE REVIEW

**Comment by danghvu** [comment]
Cool!

Could you please also commit a test to demonstrate how to use this and show that this fixes the existing issue ? (It can be the same test you wrote in the issue)

**Comment by eltongo** [comment]
While writing my test, I noticed that when writing to a 32-bit register (e.g. W0), it zeroes out the value of X0.

It seems the macro `WRITE_DWORD` (see snippet below) has an issue when writing to a `int64_t` value:

`#define WRITE_DWORD(x, w) (x = (x & ~0xffffffff) | (w & 0xffffffff))`

As seen above, in `x & ~0xffffffff`, since `0xffffffff` is an `int32_t` literal, first `~0xffffffff` is evaluated to zero, and then it is `&`ed with x, zeroing the original value out.

Shall I include another macro, something like `WRITE_DWORD_ON_QWORD` (below)?

`#define WRITE_DWORD_TO_QWORD(x, w) (x = (x & ~0xffffffffLL) | (w & 0xffffffff))`

**Comment by aquynh** [comment]
how about renaming your macro WRITE_DWORD_TO_QWORD to WRITE_DWORD, thus replace the original WRITE_DWORD, to make WRITE_DWORD work in every cases?

**Comment by aquynh** [comment]
and please fix READ_DWORD macro at the same time.

**Comment by eltongo** [comment]
Alright. The `WRITE_DWORD` macro is now fixed. `READ_DWORD` should be fine, though.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
