### PR TITLE
x86::trans: handle illegal case for opc c6/c7

### PR DESCRIPTION
**Pull request by vardyh**
Reference Intel software developer manual vol2 Appendix A Table A-6 for
detailed decoding information.

Signed-off-by: vardyh <vardyh.dev@gmail.com>

### CODE REVIEW

**Comment by aquynh** [comment]
can you provide the input triggering this issue?

another question: is this also issue for the latest Qemu version?

**Comment by vardyh** [comment]
@aquynh Did you mean a comment in the code or commit, or a testcase in sample_x86?
Regarding original Qemu, I'll check it out later.

**Comment by vardyh** [comment]
@aquynh Confirmed that original Qemu has the same issue.

**Comment by aquynh** [comment]
Yes, i mean the testcase triggering this issue.

**Comment by vardyh** [comment]
@aquynh testcase committed, it's kinda tricky, but it enumerates all the circumstances.

**Comment by aquynh** [comment]
merged, thanks!

btw, i commented out function test_i386_invalid_c6c7() so CI checks pass. in fact, the tests should be put into tests/ directory, rather than in samples/.

**Comment by vardyh** [comment]
yeah, thanks! :-D
I didn't notice the CI failure after I made the last commit. Sorry about that man :-p

**Pull request merged**
