### PR TITLE
Fix for calling uc_open() and uc_emu_start() from different threads

### PR DESCRIPTION
**Pull request by xorstream**
This is a fix attempt for calling uc_open() and uc_emu_start() from different threads as explained in issue #292 and regression test added in #320.

I have done various debug prints while trying fixes for this and it appears like this will be ok but perhaps someone with more experience with qemu internals can double check. Feel free to suggest other ways of doing this.

### CODE REVIEW

**Comment by aquynh** [comment]
a quick look, but this is strange to me: i suppose you have to remove some code, but you just added some new code. how does this solve the problem, if the same troubled code is still there?

**Comment by xorstream** [comment]
The problem stems from the fact that uc_open() locks the mutex "qemu_global_mutex" and uc_emu_start() then unlocks the same mutex "qemu_global_mutex". These mutexes must be locked an unlocked by the same thread. So if you call uc_open() from a different thread to uc_emu_start(), then the lock will occur ok, but then you will get an assert error in uc_emu_start() when you try to unlock it.

The callstack for the lock is:
uc_open()
	machine_initialize()	// vl.c
		qemu_mutex_lock_iothread(uc);
			qemu_mutex_lock(&uc->qemu_global_mutex);

The callstack for the unlock is:
uc_emu_start()				// uc.c
	vm_start()				// cpus.c
		qemu_mutex_unlock_iothread()	// main-loop.c
			qemu_mutex_unlock(&uc->qemu_global_mutex);

When I added logs to various functions to see when they are called I didn't notice any "qemu_global_mutex" action between the uc_open() and uc_emu_start() calls. So as a fix I unlock the mutex again at the end of machine_initialize() so that it is not locked when uc_open() returns. I then add an extra lock at the start of vm_start() so that it will be then locked again when it does processing that appears to make use of it. That is the reason for the code additions.

**Comment by xorstream** [comment]
Here is a debug print log I have, I'll try and explain it a bit to help make sense of it.
The important parts are mutex usage in and around the calls to uc_open() and uc_emu_start().
The first number in most prints of the address of the mutex. So 176A0058 is "qemu_global_mutex".
"thid" is the thread id of the caller.

Also mutex lock and unlock functions have a "start" and "end" postfix showing when the function is started and ended since if a lock is not ready it will stop executing until it is ready. So a "lock start" doesn't mean the lock occured, you need to find a "lock end" to know that the lock occurred.

Where you see function names with a number postfix, this means it was getting through parts of the function. So you can see by "machine_initialize 4" that no more qemu_global_mutex action occurred after machine_initialize() finished. And it is not until uc_emu_start() that qemu_global_mutex is then used again.


uc_open()
### uc->qemu_global_mutex
qemu_mutex_init:   176A0058 (thid=1178)
machine_initialize 1

-- main thread : machine_initialize() calls qemu_mutex_lock_iothread()
qemu_mutex_trylock:176A0058 (thid=1178)  start
qemu_mutex_trylock:176A0058 (thid=1178)  end
machine_initialize 2
machine_initialize 3
create thread CPU 0/TCG
qemu_cond_wait 0   176A0058 176A0074
qemu_mutex_unlock: 176A0058 (thid=1178)  start
qemu_mutex_unlock: 176A0058 (thid=1178)  end
qemu_cond_wait 1   176A0058 176A0074
qemu_tcg_cpu_thread_fn 0
qemu_tcg_cpu_thread_fn 1

-- cpu thread : qemu_tcg_cpu_thread_fn() calls qemu_mutex_lock()
qemu_mutex_lock:   176A0058 (thid=2CA8)  start
qemu_mutex_lock:   176A0058 (thid=2CA8)  end
qemu_tcg_cpu_thread_fn 2
qemu_tcg_cpu_thread_fn 3
qemu_cond_wait 2   176A0058 176A0074
qemu_cond_wait 3   176A0058 176A0074
qemu_mutex_lock:   176A0058 (thid=1178)  start		qemu_cond_wait() lock req
qemu_tcg_cpu_thread_fn 4
qemu_tcg_cpu_thread_fn 4.1
qemu_cond_wait 0   176A0058 17725B78
qemu_mutex_unlock: 176A0058 (thid=2CA8)  start
qemu_mutex_unlock: 176A0058 (thid=2CA8)  end
qemu_cond_wait 1   176A0058 17725B78

qemu_mutex_lock:   176A0058 (thid=1178)  end		qemu_cond_wait() lock get
qemu_cond_wait 4   176A0058 176A0074
machine_initialize 4

uc_mem_map()
uc_mem_write()
uc_hook_add()
---- Thread Starting ----
uc_emu_start()
qemu_cond_broadcast         17725B78
qemu_cond_wait 2   176A0058 17725B78
qemu_cond_wait 3   176A0058 17725B78
qemu_mutex_lock:   176A0058 (thid=2CA8)  start
qemu_mutex_unlock: 176A0058 (thid=2338)  start		-- my external thread (uc_emu_start() caller)
Assertion failed!

Program: F:\GitHub\unicorn\tests\regress\threaded_emu_start.exe
File: util/qemu-thread-win32.c, Line 76

**Comment by lunixbochs** [comment]
discuss in #292 - I'm inclined to think this PR shouldn't be necessary anymore

**Comment by aquynh** [comment]
Solved, thanks

**Pull request closed without merging**
