### PR TITLE
Smaller nothreads

### PR DESCRIPTION
**Pull request by cseagle**
A smaller version of my previous PR. Leaves timeouts to be handled by a watchdog thread because OSX. Builds on previous PR submitted by @lunixbochs

### CODE REVIEW

**Comment by cseagle** [comment]
I suggest holding off on this until I perform more test. @lunixbochs PR is a great first step, I would love to see that one accepted

**Comment by aquynh** [comment]
i am looking closer at this PR, thanks.

**Comment by aquynh** [comment]
on Mac, this exposes some warning on negative signed of (TARGET_PAGE_MASK << 1), that i did not see before :-/

@cseagle, do you have any issues with your tests since then?

**Comment by aquynh** [comment]
except some minor issues, this looks good. i merged it, and pushed to a new branch "no-thread". with more tests, we can merge this to "master" soon.

thanks.

**Comment by aquynh** [comment]
merged, thanks!

i will delete the "no-thread" branch after this.

**Pull request merged**
