### PR TITLE
GDT regress test

### PR DESCRIPTION
**Pull request by sashs**
GDT regress test based on my GDT setting sample

### CODE REVIEW

**Comment by cseagle** [comment]
Is this test supposed to pass or fail? Is it demonstrating a current bug with segment registers? Just checking, because it fails for me and I may have a fix

**Comment by lunixbochs** [comment]
I'm in email but I think it's supposed to pass and currently fails (assuming this is the sashs regress)

**Comment by sashs** [comment]
Currently it should fails, because if that:

> recently @sashs post a good example on setting up GDT and FS register. there are some minor issues  > there, however. i am waiting for him to send a PR to put that example under tests/regress/, then i will     > make a commit to fix this issue in the core.

**Comment by cseagle** [comment]
I address this bug in #478 with that PR, sashs' gdt regress test works, also posted sample C code that sets up a GDT and along with an FS segment

**Comment by aquynh** [comment]
merged, thanks!

**Comment by sashs** [comment]
@cseagle Did you test if my regress test works? After @aquynh merged the PR I tested it today, but for me it doesn't work.

**Comment by cseagle** [comment]
Your regress test works for me when combined with my PR #478 which hasn't been merged yet. It doesn't work for me on current unicorn-master

**Comment by sashs** [comment]
Oh, I thought your PR is merged. Then it is clear why it doesn't work.

**Comment by sparktrend** [comment]
Hi Guys,

i truly appreciate your effort on improving unicorn. I have a Windows emulator that emulates Windows executable files, which in almost all cases access FS register. My emulator started failing due to the GDT setup requirements introduced in the recent unicorn build. Based on the conversations in this thread, it seems GDT is not fully working. Could you take a look at the following issue and comment it?

https://github.com/unicorn-engine/unicorn/issues/522

Much appreciated,
Sean

**Pull request merged**
