### PR TITLE
Pull Request for Issue #364: Invalidating Translation Cache after self-modifying code

### PR DESCRIPTION
**Pull request by egberts**
It's done...

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by egberts** [comment]
Whoohoo!  Getting the hang of Git merge, particularly Github merge.

**Comment by aquynh** [comment]
you don't need to call `uc_hook_add()` separately for different type of memory accesses, but can combine them. see https://github.com/unicorn-engine/unicorn/commit/1fb5416f4ae63b9a367bd7c201da5dda741de22a

to make it easier, i added a new hook type **UC_HOOK_MEM_VALID** at https://github.com/unicorn-engine/unicorn/commit/a2ef52172c512dfbbdf0cde9316bbf33a56b9cb2

and your testcase can use it now: https://github.com/unicorn-engine/unicorn/commit/32b9deca04c2d0a98d3fb553abaa57aa97fa372c

will look closer into this issue now.

**Comment by egberts** [comment]
*ping*.  :-(

**Comment by aquynh** [comment]
I can confirm this issue, but still dont know how to fix that yet.

**Comment by egberts** [comment]
While I am doing a deep digging into the `tb_find_slow_x86_64`/`tb_find_fast_x86-64` using 10,000-instruction GDB reverse debugging session.... how far-planned is the QEMU 2.5 doing?

**Comment by aquynh** [comment]
i am still working on syncing with 2.5, focusing on ARM first. this will not be fast.

**Pull request merged**
