### PR TITLE
Removed forcing nb_regs to 0 in tcg_reg_alloc_call

### PR DESCRIPTION
**Pull request by jief666**
Forgotten hack ?

### CODE REVIEW

**Comment by 4577** [comment]
@jief666 Maybe it would be right to add a check for "defined(_MSC_VER)", in addition to "TCG_TARGET_REG_BITS == 32" in the case it would allow tests to succeed?

**Comment by jief666** [comment]
Maybe a generic test about the size of the array ? A host ARM/Windows might not exist yet, but it might soon...

**Comment by 4577** [comment]
You have also "defined(_M_ARM)" and "defined(_M_ARM64)" for this

**Comment by jief666** [comment]
Here is the proper way, I think, to resolve the problem of the dummy value in tcg_target_call_iarg_regs array.
I created a var nb_tcg_target_call_iarg_regs, set to 0 in the same case (TCG_TARGET_REG_BITS is not 64). That way tcg.c doesn't have to make any assumption about dummy value or not.

**Comment by wtdcode** [comment]
Closed due to uc2 beta release.

**Comment by jief666** [comment]
In more than 2 years, you never took my PR, even though aquynh asked me to do it.
And now you're just closing it...
Sorry to say, that's not very encouraging for contributing in the future.

Still, best of luck.

**Comment by wtdcode** [comment]
@jief666 Hello. Thanks for your contribution anyway.

I'm closing PRs since we need to refresh the community to push our new version Unicorn2. You may test your problem on our new version and if the problem still exists, I would have a look and take your PR.

Thanks for your cooperation.

**Pull request closed without merging**
