### PR TITLE
MSVC port (vardyh)

### PR DESCRIPTION
**Pull request by vardyh**
Use waitable timer to implement usleep() on Windows and get rid of usage of socket library.

### CODE REVIEW

**Comment by aquynh** [comment]
looks nice! @xorstream, do you have any comments?

**Comment by vardyh** [comment]
barrier() implementation for MSVC in updated in commit 1a4d56d2dc3d5e54b983e1cb2ea885db833ac710

**Comment by aquynh** [comment]
thanks, just a minor thing: can you indent with 4 spaces, which is the coding style that we are following?

lets see if @xorstream has any comments, so i can merge this.

**Comment by xorstream** [comment]
Looks fine to me

**Comment by vardyh** [comment]
@aquynh I adjusted the indentation and made a rebase.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
@xorstream, can you confirm that now https://github.com/unicorn-engine/unicorn/pull/740 is not needed anymore?

**Comment by xorstream** [comment]
#740 is no longer needed

**Comment by xorstream** [comment]
Now that we have MSVC native support, should we remove the MSVC binding to reduce confusion?

**Comment by aquynh** [comment]
yes, please pull req.

**Comment by xorstream** [comment]
There is a "windows_export.bat" file in the root that is used to build a static lib usable outside of mingw.
This file was added by someone else so I have left it in place but you might want to check with its author if it is still needed or not.

**Comment by aquynh** [comment]
that was from @rhelmot, but i think we still need it for Msys build. so we allow users to either use MSVC or Msys to compile Unicorn.

**Pull request merged**
