### PR TITLE
Allow passing `CMAKE_MSVC_RUNTIME_LIBRARY`

### PR DESCRIPTION
**Pull request by es3n1n**
This PR adds support for configuring the MSVC runtime library type using not only `CMAKE_C_FLAGS`, but also `CMAKE_MSVC_RUNTIME_LIBRARY`. If a conflict occurs when both `CMAKE_MSVC_RUNTIME_LIBRARY` and `CMAKE_C_FLAGS` are set, a fatal error will be raised, as we agreed in #1958.

Both cpp (cmake 3.28.1, MSVC 17.0) and rust (cargo 1.72.0) worked fine on my machine; I honestly don't think this change could break anything.

### CODE REVIEW

**Comment by wtdcode** [comment]
Looks good, waiting for CI

**Comment by wtdcode** [comment]
Oh wait, you need to rebase to dev branch.

**Comment by es3n1n** [comment]
> Oh wait, you need to rebase to dev branch.

Oops, my bad, sorry. I rebased my master to dev and changed the base branch; now, we should be good.

**Comment by wtdcode** [comment]
Thanks and welcome!

**Pull request merged**
