### PR TITLE
Uses latest qemu arm thumb load store stuff

### PR DESCRIPTION
**Pull request by catenacyber**
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10420

@aquynh :
Should there be a more global rebase on latest qemu code ?
And the other way around, should we push our changes to qemu ?

### CODE REVIEW

**Comment by catenacyber** [comment]
> did you port from the latest Qemu v3.0?

Hmm, I just looked at the code 
https://github.com/qemu/qemu/blob/master/target/arm/translate.c
So that looks like master above 3.0 

> yes, to both.

So what is the best way to do it ?
I guess that we should first import emu's fixes before submitting the ones found by oss-fuzz
I guest it would be to `git rebase` unicorn on top of qemu 3.0
But how can we do that ?

**Comment by aquynh** [comment]
i am fine with any way. we can report bugs to Qemu independently.

**Comment by aquynh** [comment]
for the record, could you put here the commit of Qemu that you ported code from?

**Comment by catenacyber** [comment]
Well, I used version https://github.com/qemu/qemu/commit/d00584b7cfab3e38f8264bebfcb6fdb02c887ade but this is not the commit which fixed the bug (there were many as I understand)

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
