### PR TITLE
limit uc_mem_(read|write) size to INT_MAX

### LINKED ISSUE #132: `size_t size` in uc_mem_read
uc_mem_read allow a `size_t size` to be passed to specify the amount to read. `size` is eventually passed to uc->read_mem on line 348 in the form of `len`, after ensuring that the memory region actually offers enough data to read on line 347. Up until that point, we're dealing entirely with 64 bit integers, assuming LP64, for example, a 64 bit Linux. However, uc->read_mem is of type
    bool (*uc_read_mem_t)(AddressSpace *as, hwaddr addr, uint8_t *buf, int len)
so `len` is cast to `int`, which is 32 bit on LP64. This will cause a truncation, and therefore less memory will be read than expected. It might be a good idea to limit `size` to be of type `int` and check that it is larger or equal to zero before doing anything, since we seem to be limited to reading INT_MAX anyway.
What do you think?

### PR DESCRIPTION
**Pull request by JonathonReinhart**
Fixes #132.

### CODE REVIEW

**Comment by aquynh** [comment]
if we limit the read/write size to INT_MAX, should we also limit the memory size of `uc_mem_map()` & `uc_mem_unmap()` to the same number?

**Comment by JonathonReinhart** [comment]
This was added simply because `cpu_physical_memory_rw` takes an `int`. I would have to review the underlying code used to implement `uc_mem_map`. But nothing is stopping one from calling read multiple times to overcome the 4GB limitation, if they have more memory mapped.

**Comment by wtdcode** [comment]
Link to #1217 for further investigation.

**Comment by wtdcode** [comment]
Fixed in df5daed. Thanks!

**Pull request closed without merging**
