### PR TITLE
make i386 instructions RDTSC and RDTSCP hookable

### LINKED ISSUE #2065: Change behaviour of the RDTSC instruction
Is it possible to tell Unicorn to change the values returned by the RDTSC instruction of amd64? I'm emulating some code that is hitting some timeout logic when I add code hooks that print debug information. So I'm looking for something the allows me to make that instruction always return 0 or have a timing system based on the number of instructions executed.

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
This patch allows the RDTSC and RDTSCP instructions to be hooked. The code is based on the CPUID hook implementation.

Fixes #2065

### CODE REVIEW

**Comment by wtdcode** [comment]
I'm good with this PR. Would you mind writing a small unit test to `tests/unit/test_x86.c`? This ensures our future release won't break your usages.

**Comment by t0rr3sp3dr0** [comment]
@wtdcod PTAL

**Comment by t0rr3sp3dr0** [comment]
@wtdcode PTAL

**Comment by wtdcode** [comment]
> @wtdcode PTAL

Looks good and thanks. Will merge once CI passes.

**Comment by t0rr3sp3dr0** [comment]
We need to rerun the failed CI job. It has failed with `mv: cannot move 'Debug' to 'instdir': Permission denied` and I don’t think this is related to my changes. I guess it’s just some flakiness.

**Comment by wtdcode** [comment]
Thanks!

**Pull request merged**
