### PR TITLE
X86 EFLAGS not synced properly.

### PR DESCRIPTION
**Pull request by farmdve**

### CODE REVIEW

**Comment by farmdve** [comment]
Sorry about the indentation, didn't notice I had mixed tabs with whitespaces.

**Comment by aquynh** [comment]
yes, can you please convert all tabs to spaces?

besides, this file also needs to be put into `tests/regress/Makefile` to compile.

thanks.

**Comment by lunixbochs** [comment]
was this actually fixed?

**Comment by farmdve** [comment]
Okay, I believe I have fixed everything.
https://github.com/unicorn-engine/unicorn/pull/246

Sorry for the new pull request, but I am very bad with git and still can't
get the hang of it.

2015-11-04 4:05 GMT+02:00 Nguyen Anh Quynh <notifications@github.com>:

**Comment by aquynh** [comment]
@lunixbochs no, the bug itself is not fixed yet.

**Pull request closed without merging**
