### PR TITLE
fixed go bindings typo

### PR DESCRIPTION
**Pull request by eqv**
Fixed broken type in go bindings

### CODE REVIEW

**Comment by lunixbochs** [comment]
can't reproduce locally - I think you have a different problem. what's your Go version?

**Comment by lunixbochs** [comment]
oh, it should work either way due to how uc_mem_region is defined. the change looks fine, but I'm still curious if this caused you any actual problems.

**Comment by eqv** [comment]
go 1.2 which afaik is the default for the current ubuntu.

**Comment by lunixbochs** [comment]
you should really be running 1.5+ (the binary distribution is very easy to use)

**Comment by aquynh** [comment]
Ryan, so do you want to merge this PR?

**Comment by lunixbochs** [comment]
yeah, I think the PR is right (not really a typo, but the "final" type is more correct even though they're equivalent)

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
