### PR TITLE
fix invalid script path (#975)

### PR DESCRIPTION
**Pull request by Sauci**

### CODE REVIEW

**Comment by aquynh** [comment]
You said this fixes Win10 issue, but will this break other platform?

**Comment by Sauci** [comment]
Not tested, I don’t have an other os right here... is it part of the CI tests performed?

**Comment by aquynh** [comment]
regarding the Python script path, why we dont have this problem with SRC_PATH before?

regarding the new APIs, i am not very sure these are very helpful, as in most cases the align & page size are fixed, and known.

**Comment by Sauci** [comment]
concerning the new API, it is a mistake from my side, reverted.
concerning the ```${SRC_PATH}``` issue, I found that the problem happens when the ```python2-setuptools``` package is not installed in cygwin.I guess this issue should be marked as won't fix? maybe an other one should be opened to update the readme?

**Comment by aquynh** [comment]
Perhapa the best option is to add that missing dependency package to
README. Could you send a pull req for that?

**Comment by Sauci** [comment]
ok, the commited changes have been reverted, and the markdown has been updated.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
