### PR TITLE
Fix a qemu bug that causes infinite hangs on the square root of malformed long doubles

### PR DESCRIPTION
**Pull request by rhelmot**
I'll submit this patch to upstream qemu too!

### CODE REVIEW

**Comment by aquynh** [comment]
can you please also provide a testcase for this issue?

**Comment by rhelmot** [comment]
```asm
  xor eax,eax
  inc eax
  push eax
  push eax
  push eax
  fld tbyte ptr [esp]
  fsqrt
```

This will hang unless the patch is applied. How can I add a testcase to unicorn?

**Comment by Nukem9** [comment]
Test case was already added by another user: https://github.com/unicorn-engine/unicorn/pull/590/commits/3eaceec07e3c603d3607fd9b13f2a3387058041d. Code is different, though.

**Comment by rhelmot** [comment]
What the fuck? I discovered this bug on my own and made the original fix on July 10... It's plausible that someone could have discovered the bug independently, I guess?

Whatever. This is a fix, and I've submitted an identical patch to upstream qemu.

**Comment by aquynh** [comment]
this looks good, as that existing testcase passed.

let see what the upstream says about this fix.

**Comment by aquynh** [comment]
is there any feedback from Qemu on this patch yet?

**Comment by rhelmot** [comment]
Qemu rejected the initial patch, requesting that we do something more
faithful to the Intel dev manual (return NaN and raise a fp exception), and
also that we apply this check to ALL floatx80 arithmetic. This patch is
currently going through code review. I'll cc you in future correspondence.

**Comment by rhelmot** [comment]
Patch got accepted upstream! The final version is drastically different from this one, though, so I'll redo the pull request.

**Pull request closed without merging**
