### PR TITLE
Changed some MSVC compatibility defines based on MSVC version.

### PR DESCRIPTION
**Pull request by xorstream**
Hopefully fixes snprintf() and isinf() compatibility defines.

### CODE REVIEW

**Comment by aquynh** [comment]
merged, but on Windows 10 + VS 2015, compilation goes further, but i still get error on missing stdbool.h & __uint128_t etc

```
1>------ Rebuild All started: Project: unicorn, Configuration: Debug x64 ------
1>  qapi-visit.c
1>  qapi-types.c
1>  uc.c
1>  vl.c
1>c:\users\me\documents\github\unicorn.git\qemu\qapi-types.h(19): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory
1>  qemu-timer-common.c
1>  qemu-thread-win32.c
1>  qemu-error.c
1>  oslib-win32.c
1>  module.c
1>  host-utils.c
1>  getauxval.c
1>  error.c
1>  cutils.c
1>  crc32c.c
1>  bitops.c
1>  bitmap.c
1>  aes.c
1>  tcg-runtime.c
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(35): error C2065: '__uint128_t' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(35): error C2146: syntax error : missing ';' before identifier 'r'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(35): error C2065: 'r' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(35): error C2146: syntax error : missing ';' before identifier 'a'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(35): warning C4552: '*' : operator has no effect; expected operator with side-effect
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(36): error C2065: 'r' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(37): error C2065: 'r' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(37): warning C4293: '>>' : shift count negative or too big, undefined behavior
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(43): error C2065: '__int128_t' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(43): error C2146: syntax error : missing ';' before identifier 'r'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(43): error C2065: 'r' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(43): error C2146: syntax error : missing ';' before identifier 'a'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(43): warning C4552: '*' : operator has no effect; expected operator with side-effect
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(44): error C2065: 'r' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(45): error C2065: 'r' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(45): warning C4293: '>>' : shift count negative or too big, undefined behavior
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(53): error C2065: '__uint128_t' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(53): error C2146: syntax error : missing ';' before identifier 'dividend'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(53): error C2065: 'dividend' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(53): error C2297: '*' : illegal, right operand has type 'uint64_t *'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(54): error C2065: '__uint128_t' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(54): error C2146: syntax error : missing ';' before identifier 'result'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(54): error C2065: 'result' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(54): error C2065: 'dividend' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(55): error C2065: 'result' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(56): error C2065: 'dividend' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(57): error C2065: 'result' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(66): error C2065: '__int128_t' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(66): error C2146: syntax error : missing ';' before identifier 'dividend'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(66): error C2065: 'dividend' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(66): error C2297: '*' : illegal, right operand has type 'int64_t *'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(67): error C2065: '__int128_t' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(67): error C2146: syntax error : missing ';' before identifier 'result'
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(67): error C2065: 'result' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(67): error C2065: 'dividend' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(68): error C2065: 'result' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(69): error C2065: 'dividend' : undeclared identifier
1>C:\Users\me\Documents\GitHub\unicorn.git\qemu\include\qemu/host-utils.h(70): error C2065: 'result' : undeclared identifier
1>  qom-qobject.c
1>  object.c
1>  Generating Code...
1>  Compiling...
1>  cpu.c
1>  container.c
1>  qstring.c
1>  qlist.c
1>  qint.c
1>  qfloat.c
1>  qerror.c
1>  qdict.c
1>  qbool.c
1>  qemu-timer.c
1>c:\users\me\documents\github\unicorn.git\qemu\qapi-types.h(19): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory
1>  qemu-log.c
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(35): error C2065: '__uint128_t' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(35): error C2146: syntax error : missing ';' before identifier 'r'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(35): error C2065: 'r' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(35): error C2146: syntax error : missing ';' before identifier 'a'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(35): warning C4552: '*' : operator has no effect; expected operator with side-effect
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(36): error C2065: 'r' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(37): error C2065: 'r' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(37): warning C4293: '>>' : shift count negative or too big, undefined behavior
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(43): error C2065: '__int128_t' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(43): error C2146: syntax error : missing ';' before identifier 'r'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(43): error C2065: 'r' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(43): error C2146: syntax error : missing ';' before identifier 'a'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(43): warning C4552: '*' : operator has no effect; expected operator with side-effect
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(44): error C2065: 'r' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(45): error C2065: 'r' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(45): warning C4293: '>>' : shift count negative or too big, undefined behavior
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(53): error C2065: '__uint128_t' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(53): error C2146: syntax error : missing ';' before identifier 'dividend'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(53): error C2065: 'dividend' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(53): error C2297: '*' : illegal, right operand has type 'uint64_t *'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(54): error C2065: '__uint128_t' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(54): error C2146: syntax error : missing ';' before identifier 'result'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(54): error C2065: 'result' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(54): error C2065: 'dividend' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(55): error C2065: 'result' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(56): error C2065: 'dividend' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(57): error C2065: 'result' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(66): error C2065: '__int128_t' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(66): error C2146: syntax error : missing ';' before identifier 'dividend'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(66): error C2065: 'dividend' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(66): error C2297: '*' : illegal, right operand has type 'int64_t *'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(67): error C2065: '__int128_t' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(67): error C2146: syntax error : missing ';' before identifier 'result'
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(67): error C2065: 'result' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(67): error C2065: 'dividend' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(68): error C2065: 'result' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(69): error C2065: 'dividend' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\include\qemu\host-utils.h(70): error C2065: 'result' : undeclared identifier
1>c:\users\me\documents\github\unicorn.git\qemu\qapi-types.h(19): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory
1>  string-input-visitor.c
1>  qmp-output-visitor.c
1>  qmp-input-visitor.c
1>  qapi-visit-core.c
1>  qapi-dealloc-visitor.c
1>  qdev.c
1>  machine.c
1>  glib_compat.c
1>  accel.c
1>c:\users\me\documents\github\unicorn.git\qemu\qapi-types.h(19): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory
1>  Generating Code...
1>  Compiling...
1>  list.c
1>  Generating Code...
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by xorstream** [comment]
The first error about stdbool.h is in qapi-types.h.
I changed the file "qemu\scripts\qapi-types.py" that generates this to include platform.h instead of stdbool.h.
I also copied this generated file to "bindings\msvc_native\qapi-types.h" and set the order of include directories so that "qapi-types.h" should be gotten from "bindings\msvc_native\qapi-types.h" instead of "qemu\qapi-types.h".

Can you please check that:
1) "qemu\scripts\qapi-types.py" shows the alteration on line 380 for #include "unicorn/platform.h
2) the file "bindings\msvc_native\qapi-types.h" exists and has #include "unicorn/platform.h on line 19
3) the msvc include dirs are ordered such that it should find "bindings\msvc_native\qapi-types.h" before qemu\qapi-types.h"

**Comment by aquynh** [comment]
do you mean i make these changes myself, or wait for your pull req?

**Comment by xorstream** [comment]
I already made changes that *should* be working for the stdbool.h issue.
But something is wrong.
Can you check the 3 things I listed above and let me klnow the state of them in your setup?
No need to change anything yet until I find out where things are going awry for you.

**Comment by xorstream** [comment]
Looking into the 2nd issue the __int128_t/__uint128_t missing.
It seems that it will only try to use these if you have CONFIG_INT128 defined (there is an ifdef around that code that uses them).

I don't define that in my project files and in my source here I don't see anywhere it could be defined. It looks like it is probably getting defined from the result of a call to "configure" and so is probably existing in "left over" config-target.h files.

Can you check if you have CONFIG_INT128 defined anywhere?
Probably in a config-target.h file.

**Comment by aquynh** [comment]
1. yes, i think you are right.
2. yes, and yes.
3. not sure what you are asking here?

**Comment by xorstream** [comment]
btw a "make clean" on your source tree would probably fix both issues, but really the msvc project should be changed so that this isn't possible to be an issue.

**Comment by xorstream** [comment]
After your response and looking at your 2nd issue with int128 I think the problem is to do with include dir ordering. ie where it chooses to get its include files from. It *should* be using the include files that I made copies of inside the "msvc_bindings" dir, but I think it is probably using some leftover versions of these files from in your qemu dirs.

I will have a little play with inserting some "bad" files in these locations to see if I can sort it out.

**Comment by aquynh** [comment]
CONFIG_INT128 is decided in qemu/configure. but since you dont run that for MSVC, i think you can handle this simply by hardcode this (i.e define it) in VS settings.

**Comment by xorstream** [comment]
The problem is that CONFIG_INT128 is being defined in your source when it shouldn't be.
So its a matter of making it NOT be defined, which should be doable by making sure we use the copies of the headers inside the "bindings/msvc_native" dir.

**Comment by aquynh** [comment]
no, i did not mean to define that in source code, but in VS settings only, so there is no change on source code.

something similar to `-DCONFIG_INT128` with Makefile, but in .vcxproj file, for example.

**Comment by xorstream** [comment]
CONFIG_INT128 should not be defined.
You are getting your error because it *is* defined for you, for some reason.

**Comment by xorstream** [comment]
Can you do a grep over your files and see where it is defined?
It is probably defined in "qemu\x86_64-softmmu\config-target.h"
If not then maybe some other leftover header file from a previous call to "configure" that is getting included in when it should not.

**Comment by xorstream** [comment]
I can replicate the qapi-types.h stdbool issue. So fixing that atm.

I tried adding "#define CONFIG_INT128 1" to "qemu\x86_64-softmmu\config-target.h" however and it does not give me the error you are seeing. So we need to work out what header file has CONFIG_INT128 defined in it in your code so I can fix it.

**Comment by aquynh** [comment]
CONFIG_INT128 can be only defined in qemu/config-host.mak, but you dont have that, so it is not defined anywhere. grep found nothing. this is strange

**Comment by xorstream** [comment]
ahh can you check your config-host.h file then please?

**Comment by aquynh** [comment]
on my Mac, the content of qemu/config-host.h is below.

```
/* Automatically generated by create_config - do not modify */
#define HOST_X86_64 1
#define CONFIG_POSIX 1
#define CONFIG_BSD 1
#define CONFIG_CPUID_H 1
```

**Comment by xorstream** [comment]
is this where you are building it using msvc?!?!

**Comment by xorstream** [comment]
is this where you are building it using msvc?!?!
msvc on mac? :)

I assume it would be like: c:\users\me\documents\github\unicorn.git\qemu\config-host.h

**Comment by aquynh** [comment]
what do you mean? i have one machine for Mac, and another for MSVC running Windows 10

**Comment by xorstream** [comment]
the config-host.h from the machine where you are trying to build for vs2015.

**Comment by xorstream** [comment]
config-host.h gets built by configure for the host compiler.
i assume you have such a file leftover on your msvc machine at c:\users\me\documents\github\unicorn.git\qemu\config-host.h that has CONFIG_INT128 defined

**Comment by aquynh** [comment]
there is no such a file on my Windows.

**Comment by xorstream** [comment]
can u do a grep for CONFIG_INT128 inside all unicorn files on your msvc machine.
it is being defined there somewhere...

**Comment by aquynh** [comment]
you have only this file https://github.com/unicorn-engine/unicorn/blob/msvc/bindings/msvc_native/config-host.h for MSVC. and that content is outdated after i cleaned up. you should copy the content of config-host.h above to replace this file.

**Comment by aquynh** [comment]
no, grep finds nothing, on my Windows

**Comment by xorstream** [comment]
That file is generated based on what the host supports.
When I searched for everything that was defined i that file, the only thing that was used was "CONFIG_CPUID_H".

So really you could remove everything from that file except the line that defines that.

**Comment by aquynh** [comment]
btw, file https://github.com/unicorn-engine/unicorn/blob/msvc/bindings/msvc_native/config-host.h is not correct: depending on host, you can have either `#define HOST_X86_64 1`, or `#define HOST_I386 1` (but not always `#define HOST_I386 1`)

**Comment by xorstream** [comment]
From the MSVC point of view HOST_I386 and HOST_X86_64 are never used, so don't matter and both can be removed.

**Comment by xorstream** [comment]
The only thing from my config-host.h that gets used anywhere is CONFIG_CPUID_H which gets used in qemu/tcg/i386/tcg-target.c

**Comment by xorstream** [comment]
What are your thoughts on having visual studio delete any "config generated files" before starting a build? These are the files that are generated when you call "configure". Since msvc doesn't use configure these files are never going to be used by msvc. Also these files are explicitly not touched by git due to their inclusion in the ".gitignore" file.

The problem is that doing: #include "somefile.h" will always try to include relative to the current directory first. And so in this case it is incorrectly including these "leftover" files that got built by calling "configure" with some other toolchain.

So the only choices are:
1) delete these leftover generated files before trying to build with msvc.
2) change all the source files that include that to handle it specially.

It seems like #1 is the cleaner choice here.

The generated files are:
qemu/qapi-types.h
qemu/qapi-types.c
qemu/qapi-visit.h
qemu/qapi-visit.c
qemu/config-host.h
qemu/?????-softmmu/config-target.h (one of these for each target cpu)

**Comment by aquynh** [comment]
yes, for those auto-gen files leftover, feel free to remove them.

**Pull request merged**
