### PR TITLE
add CMakeLists.txt

### PR DESCRIPTION
**Pull request by firodj**
I'am trying to make unicorn to be able to build with cmake. 

Current configuration is unicorn-static and for x86_64 arch only.

### CODE REVIEW

**Comment by aquynh** [comment]
Wow this is awesome!

Quick question:

- does this work on Windows now?
- how much more work to support all architectures?

Thanks!

**Comment by firodj** [comment]
Yes it works on Windows, I'am using on VS2017, and VS2019, so actually the CMakeLists.txt based on exsiting unicorn.sln. For other architecture I think the effort is same, but need to refactor to be able generate the config-host and config-client.

**Comment by aquynh** [comment]
this is a very good start! do you plan to continue working on this to support the remaining architectures?

**Comment by firodj** [comment]
yes, I'am planning to support all platform if no one trying to do. :D

**Comment by aquynh** [comment]
looking fwd to that!

**Comment by aquynh** [comment]
any progress?

i do hope that you continue this work, or somebody pick up from here, so we can build on Windows, without having to use Visual Studio project.

**Comment by aquynh** [comment]
see https://github.com/unicorn-engine/unicorn/pull/1134, which seems to be more complete

**Comment by aquynh** [comment]
close this because we already have Cmake support now, thanks!

**Pull request closed without merging**
